src/Entity/Story.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StoryRepository")
 */
class Story
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"list", "detail"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"list", "detail"})
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"list", "detail"})
     */
    private $real_title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"list", "detail"})
     */
    private $frontend;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"list", "detail"})
     */
    private $backend;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"list", "detail"})
     */
    private $start_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"detail"})
     */
    private $outside_link;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups({"detail"})
     */
    private $content;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getRealTitle(): ?string
    {
        return $this->real_title;
    }

    public function setRealTitle(string $real_title): self
    {
        $this->real_title = $real_title;

        return $this;
    }

    public function getFrontend(): ?string
    {
        return $this->frontend;
    }

    public function setFrontend(?string $frontend): self
    {
        $this->frontend = $frontend;

        return $this;
    }

    public function getBackend(): ?string
    {
        return $this->backend;
    }

    public function setBackend(?string $backend): self
    {
        $this->backend = $backend;

        return $this;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->start_at;
    }

    public function setStartAt(?\DateTimeInterface $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getOutsideLink(): ?string
    {
        return $this->outside_link;
    }

    public function setOutsideLink(?string $outside_link): self
    {
        $this->outside_link = $outside_link;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }
}

src/Form/StoryType.php
<?php

namespace App\Form;

use App\Entity\Story;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('real_title')
            ->add('frontend')
            ->add('backend')
            ->add('start_at')
            ->add('outside_link')
            ->add('content')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Story::class,
        ]);
    }
}

src/Controller/AdminApi/StoryController.php
<?php

namespace App\Controller\AdminApi;

use App\Entity\Story;
use App\Form\StoryType;
use App\Repository\StoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/story")
 */
class StoryController extends AbstractController
{
    /**
     * @Route("/", name="story_index", methods="GET")
     */
    public function index(StoryRepository $storyRepository): Response
    {
        return $this->render('story/index.html.twig', ['stories' => $storyRepository->findAll()]);
    }

    /**
     * @Route("/new", name="story_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $story = new Story();
        $form = $this->createForm(StoryType::class, $story);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($story);
            $em->flush();

            return $this->redirectToRoute('story_index');
        }

        return $this->render('story/new.html.twig', [
            'story' => $story,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="story_show", methods="GET")
     */
    public function show(Story $story): Response
    {
        return $this->render('story/show.html.twig', ['story' => $story]);
    }

    /**
     * @Route("/{id}/edit", name="story_edit", methods="GET|POST")
     */
    public function edit(Request $request, Story $story): Response
    {
        $form = $this->createForm(StoryType::class, $story);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('story_edit', ['id' => $story->getId()]);
        }

        return $this->render('story/edit.html.twig', [
            'story' => $story,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="story_delete", methods="DELETE")
     */
    public function delete(Request $request, Story $story): Response
    {
        if ($this->isCsrfTokenValid('delete'.$story->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($story);
            $em->flush();
        }

        return $this->redirectToRoute('story_index');
    }
}

src/Controller/Api/StoryController.php
<?php

namespace App\Controller\Api;

use App\Entity\Story;
use App\Repository\StoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("story")
 */
class StoryController extends Controller
{
    use JsonApi;

    /**
     * @Route("s", methods={"GET"})
     */
    public function index(StoryRepository $repository)
    {
        $data = $repository->findAll();
        return $this->createJsonSerializeResponse($data, array("list"));
    }

    /**
     * @Route("/{id}", methods={"GET"})
     */
    public function show(Story $story)
    {
        return $this->createJsonSerializeResponse($story, array("detail"));
    }

    /**
     * @Route("/{id}", methods={"POST", "PUT"})
     */
    public function edit(Story $story)
    {
        return $this->createJsonSerializeResponse($story, array("detail"));
    }
}

templates/story/_delete_form.html.twig
<form method="post" action="{{ path('story_delete', {'id': story.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ story.id) }}">
    <button class="btn">Delete</button>
</form>

templates/story/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/story/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Story{% endblock %}

{% block body %}
    <h1>Edit Story</h1>

    {{ include('story/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('story_index') }}">back to list</a>

    {{ include('story/_delete_form.html.twig') }}
{% endblock %}

templates/story/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Story index{% endblock %}

{% block body %}
    <h1>Story index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Real_title</th>
                <th>Frontend</th>
                <th>Backend</th>
                <th>Start_at</th>
                <th>Outside_link</th>
                <th>Content</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for story in stories %}
            <tr>
                <td>{{ story.id }}</td>
                <td>{{ story.title }}</td>
                <td>{{ story.realTitle }}</td>
                <td>{{ story.frontend }}</td>
                <td>{{ story.backend }}</td>
                <td>{{ story.startAt ? story.startAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ story.outsideLink }}</td>
                <td>{{ story.content }}</td>
                <td>
                    <a href="{{ path('story_show', {'id': story.id}) }}">show</a>
                    <a href="{{ path('story_edit', {'id': story.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('story_new') }}">Create new</a>
{% endblock %}

templates/story/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Story{% endblock %}

{% block body %}
    <h1>Create new Story</h1>

    {{ include('story/_form.html.twig') }}

    <a href="{{ path('story_index') }}">back to list</a>
{% endblock %}

templates/story/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Story{% endblock %}

{% block body %}
    <h1>Story</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ story.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ story.title }}</td>
            </tr>
            <tr>
                <th>Real_title</th>
                <td>{{ story.realTitle }}</td>
            </tr>
            <tr>
                <th>Frontend</th>
                <td>{{ story.frontend }}</td>
            </tr>
            <tr>
                <th>Backend</th>
                <td>{{ story.backend }}</td>
            </tr>
            <tr>
                <th>Start_at</th>
                <td>{{ story.startAt ? story.startAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Outside_link</th>
                <td>{{ story.outsideLink }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ story.content }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('story_index') }}">back to list</a>

    <a href="{{ path('story_edit', {'id': story.id}) }}">edit</a>

    {{ include('story/_delete_form.html.twig') }}
{% endblock %}